version: '3.8'
volumes:
  app:
  postgres: 
services:
  app:
    image: 'safedate:latest'
    ports:
      - "8080:8080"
    expose:
      - 8080
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL81Dialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=public
          
  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=public
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD="trust"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433