FROM openjdk:17-alpine
EXPOSE 8080
ARG JAR_FILE=*.jar
COPY ${JAR_FILE} application.jar
ENTRYPOINT ["java", "-jar", "application.jar"]

# FROM postgres:14.5
# ENV POSTGRES_DB safedate
# ENV POSTGRES_PASSWORD admin
# ENV POSTGRES_USER postgres
# EXPOSE 5433